# Generated by Django 6.0.3 on 2026-03-26 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resend_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('resend_from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('twilio_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracao',
                'verbose_name_plural': 'Configuracoes',
            },
        ),
    ]
