# Generated by Django 6.0.3 on 2026-04-02 01:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_invite_organizationmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Configuracoes do Usuario'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='user',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='user',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='user',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='user',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nome_fantasia',
        ),
        migrations.RemoveField(
            model_name='user',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='user',
            name='razao_social',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='invite',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
