# Generated by Django 6.0.3 on 2026-04-03 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usersettings_options_remove_user_bairro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_marketing', models.BooleanField(default=True)),
                ('sms_marketing', models.BooleanField(default=True)),
                ('contacts', models.BooleanField(default=True)),
                ('scheduling', models.BooleanField(default=True)),
                ('analytics', models.BooleanField(default=True)),
                ('integrations', models.BooleanField(default=False)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.organizationmember')),
            ],
            options={
                'verbose_name': 'Permissao',
                'verbose_name_plural': 'Permissoes',
            },
        ),
    ]
