# Generated by Django 6.0.3 on 2026-04-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_sms_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='nome_remetente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
