# Generated by Django 6.0.3 on 2026-04-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usersettings_nome_remetente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='resend_api_key',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='resend_from_email',
        ),
    ]
