[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && gunicorn core.wsgi --bind 0.0.0.0:$PORT"
healthcheckPath = "/accounts/login/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"