# Generated by Django 6.0.3 on 2026-03-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='reply_to',
            field=models.EmailField(blank=True, help_text='E-mail para onde as respostas serão enviadas', max_length=254, null=True),
        ),
    ]
