# Generated by Django 6.0.3 on 2026-03-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('both', 'E-mail e SMS')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sms_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('agendada', 'Agendada'), ('enviando', 'Enviando'), ('concluida', 'Concluida'), ('erro', 'Erro')], default='rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='subject',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
