# Generated by Django 6.0.3 on 2026-04-02 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usersettings_options_remove_user_bairro_and_more'),
        ('campaigns', '0003_campaign_channel_campaign_sms_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.organization'),
        ),
    ]
