# Generated by Django 6.0.3 on 2026-04-03 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_memberpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_cpf_cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(max_length=500)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('CREDIT_CARD', 'Cartão de Crédito')], default='PIX', max_length=20)),
                ('notify_via', models.CharField(choices=[('none', 'Não notificar'), ('email', 'E-mail'), ('sms', 'SMS'), ('both', 'E-mail e SMS')], default='email', max_length=10)),
                ('asaas_id', models.CharField(blank=True, max_length=100, null=True)),
                ('asaas_url', models.URLField(blank=True, null=True)),
                ('pix_qrcode', models.TextField(blank=True, null=True)),
                ('pix_payload', models.TextField(blank=True, null=True)),
                ('boleto_url', models.URLField(blank=True, null=True)),
                ('boleto_code', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RECEIVED', 'Pago'), ('CONFIRMED', 'Confirmado'), ('OVERDUE', 'Vencido'), ('REFUNDED', 'Estornado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'ordering': ['-created_at'],
            },
        ),
    ]
