# Generated by Django 6.0.3 on 2026-04-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='notify_via',
            field=models.CharField(choices=[('none', 'Não notificar'), ('email', 'E-mail')], default='email', max_length=10),
        ),
    ]
